# estoo es la imagen que queremos usar
FROM openjdk:17-jdk-alpine
# comando que copiara nuestra aplicacion en la imagen
COPY target/webspring-1.jar webspring-1.jar
#ejecutarar dentro de la imagen 
ENTRYPOINT ["java", "-jar", "/webspring-1.jar"]
#expone el puerto
EXPOSE 8090